//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encore.WebServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://encore.ceh.ac.uk/", ConfigurationName="Encore.WebServices.encoreSoap")]
    public interface encoreSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://encore.ceh.ac.uk/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://encore.ceh.ac.uk/HelloWorld", ReplyAction="*")]
        System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState);
        
        string EndHelloWorld(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'GetSitesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://encore.ceh.ac.uk/GetSites", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Encore.WebServices.GetSitesResponse GetSites(Encore.WebServices.GetSitesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://encore.ceh.ac.uk/GetSites", ReplyAction="*")]
        System.IAsyncResult BeginGetSites(Encore.WebServices.GetSitesRequest request, System.AsyncCallback callback, object asyncState);
        
        Encore.WebServices.GetSitesResponse EndGetSites(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'GetFieldsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://encore.ceh.ac.uk/GetFields", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Encore.WebServices.GetFieldsResponse GetFields(Encore.WebServices.GetFieldsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://encore.ceh.ac.uk/GetFields", ReplyAction="*")]
        System.IAsyncResult BeginGetFields(Encore.WebServices.GetFieldsRequest request, System.AsyncCallback callback, object asyncState);
        
        Encore.WebServices.GetFieldsResponse EndGetFields(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'GetSummaryResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://encore.ceh.ac.uk/GetSummary", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Encore.WebServices.GetSummaryResponse GetSummary(Encore.WebServices.GetSummaryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://encore.ceh.ac.uk/GetSummary", ReplyAction="*")]
        System.IAsyncResult BeginGetSummary(Encore.WebServices.GetSummaryRequest request, System.AsyncCallback callback, object asyncState);
        
        Encore.WebServices.GetSummaryResponse EndGetSummary(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://encore.ceh.ac.uk/GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Encore.WebServices.DataPackage GetData(int[] fields, int[] sites, System.DateTime datefrom, System.DateTime dateto);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://encore.ceh.ac.uk/GetData", ReplyAction="*")]
        System.IAsyncResult BeginGetData(int[] fields, int[] sites, System.DateTime datefrom, System.DateTime dateto, System.AsyncCallback callback, object asyncState);
        
        Encore.WebServices.DataPackage EndGetData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://encore.ceh.ac.uk/TestGetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Encore.WebServices.DataPackage TestGetData(int field, int site, System.DateTime datefrom, System.DateTime dateto);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://encore.ceh.ac.uk/TestGetData", ReplyAction="*")]
        System.IAsyncResult BeginTestGetData(int field, int site, System.DateTime datefrom, System.DateTime dateto, System.AsyncCallback callback, object asyncState);
        
        Encore.WebServices.DataPackage EndTestGetData(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://encore.ceh.ac.uk/")]
    public partial class Site : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://encore.ceh.ac.uk/")]
    public partial class DataPackageRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FieldValue[] valuesField;
        
        private System.DateTime rowDateField;
        
        private int siteIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FieldValue[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime RowDate {
            get {
                return this.rowDateField;
            }
            set {
                this.rowDateField = value;
                this.RaisePropertyChanged("RowDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int SiteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
                this.RaisePropertyChanged("SiteID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://encore.ceh.ac.uk/")]
    public partial class FieldValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int fieldIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int FieldID {
            get {
                return this.fieldIDField;
            }
            set {
                this.fieldIDField = value;
                this.RaisePropertyChanged("FieldID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://encore.ceh.ac.uk/")]
    public partial class DataPackage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DataPackageRow[] rowsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DataPackageRow[] Rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
                this.RaisePropertyChanged("Rows");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://encore.ceh.ac.uk/")]
    public partial class FieldDataSummary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FieldValue[] numberOfRowsField;
        
        private int siteIDField;
        
        private System.DateTime minDateField;
        
        private System.DateTime maxDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FieldValue[] NumberOfRows {
            get {
                return this.numberOfRowsField;
            }
            set {
                this.numberOfRowsField = value;
                this.RaisePropertyChanged("NumberOfRows");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int SiteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
                this.RaisePropertyChanged("SiteID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime MinDate {
            get {
                return this.minDateField;
            }
            set {
                this.minDateField = value;
                this.RaisePropertyChanged("MinDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime MaxDate {
            get {
                return this.maxDateField;
            }
            set {
                this.maxDateField = value;
                this.RaisePropertyChanged("MaxDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://encore.ceh.ac.uk/")]
    public partial class Field : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string unitField;
        
        private string dataTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("Unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
                this.RaisePropertyChanged("DataType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSites", WrapperNamespace="http://encore.ceh.ac.uk/", IsWrapped=true)]
    public partial class GetSitesRequest {
        
        public GetSitesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSitesResponse", WrapperNamespace="http://encore.ceh.ac.uk/", IsWrapped=true)]
    public partial class GetSitesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://encore.ceh.ac.uk/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Encore.WebServices.Site[] GetSitesResult;
        
        public GetSitesResponse() {
        }
        
        public GetSitesResponse(Encore.WebServices.Site[] GetSitesResult) {
            this.GetSitesResult = GetSitesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFields", WrapperNamespace="http://encore.ceh.ac.uk/", IsWrapped=true)]
    public partial class GetFieldsRequest {
        
        public GetFieldsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFieldsResponse", WrapperNamespace="http://encore.ceh.ac.uk/", IsWrapped=true)]
    public partial class GetFieldsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://encore.ceh.ac.uk/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Encore.WebServices.Field[] GetFieldsResult;
        
        public GetFieldsResponse() {
        }
        
        public GetFieldsResponse(Encore.WebServices.Field[] GetFieldsResult) {
            this.GetFieldsResult = GetFieldsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSummary", WrapperNamespace="http://encore.ceh.ac.uk/", IsWrapped=true)]
    public partial class GetSummaryRequest {
        
        public GetSummaryRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSummaryResponse", WrapperNamespace="http://encore.ceh.ac.uk/", IsWrapped=true)]
    public partial class GetSummaryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://encore.ceh.ac.uk/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Encore.WebServices.FieldDataSummary[] GetSummaryResult;
        
        public GetSummaryResponse() {
        }
        
        public GetSummaryResponse(Encore.WebServices.FieldDataSummary[] GetSummaryResult) {
            this.GetSummaryResult = GetSummaryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface encoreSoapChannel : Encore.WebServices.encoreSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSitesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSitesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Encore.WebServices.Site[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Encore.WebServices.Site[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFieldsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFieldsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Encore.WebServices.Field[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Encore.WebServices.Field[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSummaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSummaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Encore.WebServices.FieldDataSummary[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Encore.WebServices.FieldDataSummary[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Encore.WebServices.DataPackage Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Encore.WebServices.DataPackage)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestGetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public TestGetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Encore.WebServices.DataPackage Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Encore.WebServices.DataPackage)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class encoreSoapClient : System.ServiceModel.ClientBase<Encore.WebServices.encoreSoap>, Encore.WebServices.encoreSoap {
        
        private BeginOperationDelegate onBeginHelloWorldDelegate;
        
        private EndOperationDelegate onEndHelloWorldDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSitesDelegate;
        
        private EndOperationDelegate onEndGetSitesDelegate;
        
        private System.Threading.SendOrPostCallback onGetSitesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFieldsDelegate;
        
        private EndOperationDelegate onEndGetFieldsDelegate;
        
        private System.Threading.SendOrPostCallback onGetFieldsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSummaryDelegate;
        
        private EndOperationDelegate onEndGetSummaryDelegate;
        
        private System.Threading.SendOrPostCallback onGetSummaryCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDataDelegate;
        
        private EndOperationDelegate onEndGetDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginTestGetDataDelegate;
        
        private EndOperationDelegate onEndTestGetDataDelegate;
        
        private System.Threading.SendOrPostCallback onTestGetDataCompletedDelegate;
        
        public encoreSoapClient() {
        }
        
        public encoreSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public encoreSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public encoreSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public encoreSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<HelloWorldCompletedEventArgs> HelloWorldCompleted;
        
        public event System.EventHandler<GetSitesCompletedEventArgs> GetSitesCompleted;
        
        public event System.EventHandler<GetFieldsCompletedEventArgs> GetFieldsCompleted;
        
        public event System.EventHandler<GetSummaryCompletedEventArgs> GetSummaryCompleted;
        
        public event System.EventHandler<GetDataCompletedEventArgs> GetDataCompleted;
        
        public event System.EventHandler<TestGetDataCompletedEventArgs> TestGetDataCompleted;
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorld(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndHelloWorld(System.IAsyncResult result) {
            return base.Channel.EndHelloWorld(result);
        }
        
        private System.IAsyncResult OnBeginHelloWorld(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginHelloWorld(callback, asyncState);
        }
        
        private object[] OnEndHelloWorld(System.IAsyncResult result) {
            string retVal = this.EndHelloWorld(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldCompleted(object state) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        public void HelloWorldAsync(object userState) {
            if ((this.onBeginHelloWorldDelegate == null)) {
                this.onBeginHelloWorldDelegate = new BeginOperationDelegate(this.OnBeginHelloWorld);
            }
            if ((this.onEndHelloWorldDelegate == null)) {
                this.onEndHelloWorldDelegate = new EndOperationDelegate(this.OnEndHelloWorld);
            }
            if ((this.onHelloWorldCompletedDelegate == null)) {
                this.onHelloWorldCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldDelegate, null, this.onEndHelloWorldDelegate, this.onHelloWorldCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Encore.WebServices.GetSitesResponse Encore.WebServices.encoreSoap.GetSites(Encore.WebServices.GetSitesRequest request) {
            return base.Channel.GetSites(request);
        }
        
        public Encore.WebServices.Site[] GetSites() {
            Encore.WebServices.GetSitesRequest inValue = new Encore.WebServices.GetSitesRequest();
            Encore.WebServices.GetSitesResponse retVal = ((Encore.WebServices.encoreSoap)(this)).GetSites(inValue);
            return retVal.GetSitesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Encore.WebServices.encoreSoap.BeginGetSites(Encore.WebServices.GetSitesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSites(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetSites(System.AsyncCallback callback, object asyncState) {
            Encore.WebServices.GetSitesRequest inValue = new Encore.WebServices.GetSitesRequest();
            return ((Encore.WebServices.encoreSoap)(this)).BeginGetSites(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Encore.WebServices.GetSitesResponse Encore.WebServices.encoreSoap.EndGetSites(System.IAsyncResult result) {
            return base.Channel.EndGetSites(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Encore.WebServices.Site[] EndGetSites(System.IAsyncResult result) {
            Encore.WebServices.GetSitesResponse retVal = ((Encore.WebServices.encoreSoap)(this)).EndGetSites(result);
            return retVal.GetSitesResult;
        }
        
        private System.IAsyncResult OnBeginGetSites(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetSites(callback, asyncState);
        }
        
        private object[] OnEndGetSites(System.IAsyncResult result) {
            Encore.WebServices.Site[] retVal = this.EndGetSites(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSitesCompleted(object state) {
            if ((this.GetSitesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSitesCompleted(this, new GetSitesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSitesAsync() {
            this.GetSitesAsync(null);
        }
        
        public void GetSitesAsync(object userState) {
            if ((this.onBeginGetSitesDelegate == null)) {
                this.onBeginGetSitesDelegate = new BeginOperationDelegate(this.OnBeginGetSites);
            }
            if ((this.onEndGetSitesDelegate == null)) {
                this.onEndGetSitesDelegate = new EndOperationDelegate(this.OnEndGetSites);
            }
            if ((this.onGetSitesCompletedDelegate == null)) {
                this.onGetSitesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSitesCompleted);
            }
            base.InvokeAsync(this.onBeginGetSitesDelegate, null, this.onEndGetSitesDelegate, this.onGetSitesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Encore.WebServices.GetFieldsResponse Encore.WebServices.encoreSoap.GetFields(Encore.WebServices.GetFieldsRequest request) {
            return base.Channel.GetFields(request);
        }
        
        public Encore.WebServices.Field[] GetFields() {
            Encore.WebServices.GetFieldsRequest inValue = new Encore.WebServices.GetFieldsRequest();
            Encore.WebServices.GetFieldsResponse retVal = ((Encore.WebServices.encoreSoap)(this)).GetFields(inValue);
            return retVal.GetFieldsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Encore.WebServices.encoreSoap.BeginGetFields(Encore.WebServices.GetFieldsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFields(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetFields(System.AsyncCallback callback, object asyncState) {
            Encore.WebServices.GetFieldsRequest inValue = new Encore.WebServices.GetFieldsRequest();
            return ((Encore.WebServices.encoreSoap)(this)).BeginGetFields(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Encore.WebServices.GetFieldsResponse Encore.WebServices.encoreSoap.EndGetFields(System.IAsyncResult result) {
            return base.Channel.EndGetFields(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Encore.WebServices.Field[] EndGetFields(System.IAsyncResult result) {
            Encore.WebServices.GetFieldsResponse retVal = ((Encore.WebServices.encoreSoap)(this)).EndGetFields(result);
            return retVal.GetFieldsResult;
        }
        
        private System.IAsyncResult OnBeginGetFields(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetFields(callback, asyncState);
        }
        
        private object[] OnEndGetFields(System.IAsyncResult result) {
            Encore.WebServices.Field[] retVal = this.EndGetFields(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFieldsCompleted(object state) {
            if ((this.GetFieldsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFieldsCompleted(this, new GetFieldsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFieldsAsync() {
            this.GetFieldsAsync(null);
        }
        
        public void GetFieldsAsync(object userState) {
            if ((this.onBeginGetFieldsDelegate == null)) {
                this.onBeginGetFieldsDelegate = new BeginOperationDelegate(this.OnBeginGetFields);
            }
            if ((this.onEndGetFieldsDelegate == null)) {
                this.onEndGetFieldsDelegate = new EndOperationDelegate(this.OnEndGetFields);
            }
            if ((this.onGetFieldsCompletedDelegate == null)) {
                this.onGetFieldsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFieldsCompleted);
            }
            base.InvokeAsync(this.onBeginGetFieldsDelegate, null, this.onEndGetFieldsDelegate, this.onGetFieldsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Encore.WebServices.GetSummaryResponse Encore.WebServices.encoreSoap.GetSummary(Encore.WebServices.GetSummaryRequest request) {
            return base.Channel.GetSummary(request);
        }
        
        public Encore.WebServices.FieldDataSummary[] GetSummary() {
            Encore.WebServices.GetSummaryRequest inValue = new Encore.WebServices.GetSummaryRequest();
            Encore.WebServices.GetSummaryResponse retVal = ((Encore.WebServices.encoreSoap)(this)).GetSummary(inValue);
            return retVal.GetSummaryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Encore.WebServices.encoreSoap.BeginGetSummary(Encore.WebServices.GetSummaryRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSummary(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetSummary(System.AsyncCallback callback, object asyncState) {
            Encore.WebServices.GetSummaryRequest inValue = new Encore.WebServices.GetSummaryRequest();
            return ((Encore.WebServices.encoreSoap)(this)).BeginGetSummary(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Encore.WebServices.GetSummaryResponse Encore.WebServices.encoreSoap.EndGetSummary(System.IAsyncResult result) {
            return base.Channel.EndGetSummary(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Encore.WebServices.FieldDataSummary[] EndGetSummary(System.IAsyncResult result) {
            Encore.WebServices.GetSummaryResponse retVal = ((Encore.WebServices.encoreSoap)(this)).EndGetSummary(result);
            return retVal.GetSummaryResult;
        }
        
        private System.IAsyncResult OnBeginGetSummary(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetSummary(callback, asyncState);
        }
        
        private object[] OnEndGetSummary(System.IAsyncResult result) {
            Encore.WebServices.FieldDataSummary[] retVal = this.EndGetSummary(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSummaryCompleted(object state) {
            if ((this.GetSummaryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSummaryCompleted(this, new GetSummaryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSummaryAsync() {
            this.GetSummaryAsync(null);
        }
        
        public void GetSummaryAsync(object userState) {
            if ((this.onBeginGetSummaryDelegate == null)) {
                this.onBeginGetSummaryDelegate = new BeginOperationDelegate(this.OnBeginGetSummary);
            }
            if ((this.onEndGetSummaryDelegate == null)) {
                this.onEndGetSummaryDelegate = new EndOperationDelegate(this.OnEndGetSummary);
            }
            if ((this.onGetSummaryCompletedDelegate == null)) {
                this.onGetSummaryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSummaryCompleted);
            }
            base.InvokeAsync(this.onBeginGetSummaryDelegate, null, this.onEndGetSummaryDelegate, this.onGetSummaryCompletedDelegate, userState);
        }
        
        public Encore.WebServices.DataPackage GetData(int[] fields, int[] sites, System.DateTime datefrom, System.DateTime dateto) {
            return base.Channel.GetData(fields, sites, datefrom, dateto);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetData(int[] fields, int[] sites, System.DateTime datefrom, System.DateTime dateto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetData(fields, sites, datefrom, dateto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Encore.WebServices.DataPackage EndGetData(System.IAsyncResult result) {
            return base.Channel.EndGetData(result);
        }
        
        private System.IAsyncResult OnBeginGetData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int[] fields = ((int[])(inValues[0]));
            int[] sites = ((int[])(inValues[1]));
            System.DateTime datefrom = ((System.DateTime)(inValues[2]));
            System.DateTime dateto = ((System.DateTime)(inValues[3]));
            return this.BeginGetData(fields, sites, datefrom, dateto, callback, asyncState);
        }
        
        private object[] OnEndGetData(System.IAsyncResult result) {
            Encore.WebServices.DataPackage retVal = this.EndGetData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDataCompleted(object state) {
            if ((this.GetDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDataAsync(int[] fields, int[] sites, System.DateTime datefrom, System.DateTime dateto) {
            this.GetDataAsync(fields, sites, datefrom, dateto, null);
        }
        
        public void GetDataAsync(int[] fields, int[] sites, System.DateTime datefrom, System.DateTime dateto, object userState) {
            if ((this.onBeginGetDataDelegate == null)) {
                this.onBeginGetDataDelegate = new BeginOperationDelegate(this.OnBeginGetData);
            }
            if ((this.onEndGetDataDelegate == null)) {
                this.onEndGetDataDelegate = new EndOperationDelegate(this.OnEndGetData);
            }
            if ((this.onGetDataCompletedDelegate == null)) {
                this.onGetDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataDelegate, new object[] {
                        fields,
                        sites,
                        datefrom,
                        dateto}, this.onEndGetDataDelegate, this.onGetDataCompletedDelegate, userState);
        }
        
        public Encore.WebServices.DataPackage TestGetData(int field, int site, System.DateTime datefrom, System.DateTime dateto) {
            return base.Channel.TestGetData(field, site, datefrom, dateto);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginTestGetData(int field, int site, System.DateTime datefrom, System.DateTime dateto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTestGetData(field, site, datefrom, dateto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Encore.WebServices.DataPackage EndTestGetData(System.IAsyncResult result) {
            return base.Channel.EndTestGetData(result);
        }
        
        private System.IAsyncResult OnBeginTestGetData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int field = ((int)(inValues[0]));
            int site = ((int)(inValues[1]));
            System.DateTime datefrom = ((System.DateTime)(inValues[2]));
            System.DateTime dateto = ((System.DateTime)(inValues[3]));
            return this.BeginTestGetData(field, site, datefrom, dateto, callback, asyncState);
        }
        
        private object[] OnEndTestGetData(System.IAsyncResult result) {
            Encore.WebServices.DataPackage retVal = this.EndTestGetData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTestGetDataCompleted(object state) {
            if ((this.TestGetDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TestGetDataCompleted(this, new TestGetDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TestGetDataAsync(int field, int site, System.DateTime datefrom, System.DateTime dateto) {
            this.TestGetDataAsync(field, site, datefrom, dateto, null);
        }
        
        public void TestGetDataAsync(int field, int site, System.DateTime datefrom, System.DateTime dateto, object userState) {
            if ((this.onBeginTestGetDataDelegate == null)) {
                this.onBeginTestGetDataDelegate = new BeginOperationDelegate(this.OnBeginTestGetData);
            }
            if ((this.onEndTestGetDataDelegate == null)) {
                this.onEndTestGetDataDelegate = new EndOperationDelegate(this.OnEndTestGetData);
            }
            if ((this.onTestGetDataCompletedDelegate == null)) {
                this.onTestGetDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTestGetDataCompleted);
            }
            base.InvokeAsync(this.onBeginTestGetDataDelegate, new object[] {
                        field,
                        site,
                        datefrom,
                        dateto}, this.onEndTestGetDataDelegate, this.onTestGetDataCompletedDelegate, userState);
        }
    }
}
